server:
  port: 8080

security:
  oauth2:
    resource:
      filter-order: 3
    client:
      client-id: web-app
      access-token-uri: http://localhost:8080/web-app/auth/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 15000
    pool:
      max-active: 30 # 最大连接数量，默认8，能够同时建立的最大连接数
      max-idle: 20 # 最大空闲连接数量，默认8，空闲连接数大于maxIdle时，将进行回收
      max-wait: 1000 # 最大阻塞等待时间，默认-1
      min-idle: 5 # 最小空闲数，默认0，低于minIdle时，将创建新的连接



